In [8]:
import numpy as np
b = np.array([21,4.0,3.2,0,16])
b.ndim # this is a scalar, because its ndim is 1

1

In [11]:
c = np.array([[1,2,3,4],[0,3,1,4]])
c.ndim # this is a matrix, because its ndim is >=2

2

In [51]:
# generating a random list of floats and inputting them into the array
import random
rand=[]
for i in range(5):
   rand.append(round(random.random(),2))
d = np.array(rand)
print(d)
d.shape

[0.04 0.01 0.71 0.18 0.07]


(5,)

In [116]:
# generating a random list of floats and inputting them into the array
import random
rand_row=[]
rand_col=[]
for i in range(5):
   rand_row.append(round(random.random(),2))
   rand_col.append(round(random.random(),2))


d = np.array([rand_row,rand_col])
print(d)
d.shape

[[0.08 0.36 0.13 0.36 0.43]
 [0.93 0.24 0.04 0.64 0.51]]


(2, 5)

In [117]:
my_list=[[1,2,3],[4,5,6],[7,8,9]]
e = np.array(my_list)
e.shape

(3, 3)

In [69]:
np.linspace(random.randint(2,10),random.randint(2,10))

array([4.        , 4.06122449, 4.12244898, 4.18367347, 4.24489796,
       4.30612245, 4.36734694, 4.42857143, 4.48979592, 4.55102041,
       4.6122449 , 4.67346939, 4.73469388, 4.79591837, 4.85714286,
       4.91836735, 4.97959184, 5.04081633, 5.10204082, 5.16326531,
       5.2244898 , 5.28571429, 5.34693878, 5.40816327, 5.46938776,
       5.53061224, 5.59183673, 5.65306122, 5.71428571, 5.7755102 ,
       5.83673469, 5.89795918, 5.95918367, 6.02040816, 6.08163265,
       6.14285714, 6.20408163, 6.26530612, 6.32653061, 6.3877551 ,
       6.44897959, 6.51020408, 6.57142857, 6.63265306, 6.69387755,
       6.75510204, 6.81632653, 6.87755102, 6.93877551, 7.        ])

In [72]:
np.linspace(2,4)

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [90]:
# to create a certain number of random values in an array
np.arange(10).reshape(2,5)
np.arange(20).reshape(1,20)
# you will get an error if you do not get the right dimensions

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [124]:
# operations on the arrays
a = np.array([i for i in range(1,6)])
b = np.array([i for i in range(6,11)])

print("a = ",a)
print("b = ",b)
# addition operation
print("Addition\n", (a+b))
# dot operation
print("dot = ",a.dot(b))

# multiplication operation
print("multiplication = ", a*b)

a =  [1 2 3 4 5]
b =  [ 6  7  8  9 10]
Addition
 [ 7  9 11 13 15]
dot =  130
multiplication =  [ 6 14 24 36 50]


In [128]:
# shape manipulation
# When you put -1 in the shape, numpy infers it from the other dimensions, 
# that is replaces -1 with product of all dimensions of a / product of all specified shapes
f = np.arange(50)
f.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [132]:
# indexing
f = np.arange(10)
print(f)
f[3]

[0 1 2 3 4 5 6 7 8 9]


3

In [136]:
# slicing
f[:5:2]

array([0, 2, 4])

In [173]:
# finding the middle values
g = np.arange(10)
print(g)
g = g.reshape(2,-1)
print(g)
print(g[0][2])
print(g[1][2])
# g[2,2]
# using slicing to find the the middle value
g[0:2,2:3]


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
2
7


array([[2],
       [7]])

In [192]:
# creating random values
h = np.random.randn(10)

print(h)
# calculating the mean
np.max(h)

[-2.65421167  0.87880463  0.2637726  -0.56045078 -0.39665411 -0.26475692
 -0.20130557 -1.00312848 -0.10351941 -1.684562  ]


0.8788046265284194

In [ ]:
# calculate the standard deviation
